# Generated by Django 5.2.4 on 2025-08-03 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meallog',
            old_name='food_name',
            new_name='meal',
        ),
        migrations.RemoveField(
            model_name='meallog',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='meallog',
            name='meal_type',
        ),
        migrations.RemoveField(
            model_name='workoutlog',
            name='calories_burned',
        ),
        migrations.RemoveField(
            model_name='workoutlog',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='meallog',
            name='date',
            field=models.DateField(default=datetime.date(2025, 8, 3)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='duration',
            field=models.PositiveIntegerField(default=30, help_text='Duration in minutes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meallog',
            name='calories',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
