# Generated by Django 5.2.4 on 2025-08-05 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_rename_food_name_meallog_meal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meallog',
            name='date',
        ),
        migrations.AddField(
            model_name='meallog',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
